services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: bfmhno3.github.io
    userns_mode: keep-id

    command: >
      sh -c "
      bundle config mirror.https://rubygems.org https://mirrors.tuna.tsinghua.edu.cn/rubygems/ &&
      bundle check || bundle install &&
      bundle exec jekyll serve --watch --force_polling --future --verbose --host 0.0.0.0
      "
    ports:
      - "4000:4000"
      # - "35729:35729"  # livereload 端口
    volumes:
      - .:/srv/jekyll  # 将当前目录挂载到容器内的 /srv/jekyll
      - bundle_cache:/usr/local/bundle  # 持久化 Ruby gems，避免每次启动都重新安装
    environment:
      - BUNDLE_PATH=/usr/local/bundle  # 指定 gems 安装路径

volumes:
  bundle_cache:
